### ISSUE TITLE
Generating new new characters

### ISSUE THREAD

**Issue by fire17** [multiavatar/Multiavatar#11]
Hi there ! 
First of all this is really awesome :) thank you for making this awesome ability!
I've managed to run locally and get images generated :D
Now starting to study up on svgs and how to make them, would like to draw my own art style and have it generate a new set of results

Was wondering if you could suggest how you made your images, which program you used, and if there's any specific formatting needed to have it work with the app , like having exactly 6 sections, etc 

Thanks a lot ! Have a good one !

**Comment by fire17** [comment]
ReReading the docs with closer attention
You've pointed to Inkscape
I'll check it out
Lemme know if there's anything else I need to change or do you recommend 🙏

**Comment by giekaton** [comment]
Hi, thank you for the feedback. Best luck with building your own library based on Multiavatar. I will try to help.

Yes, good idea to check the README first, as there are many things explained.

For shapes editing, you can use Inkscape, which is free. I was also using CorelDraw and Illustrator, but final files were prepared and exported with Inkscape.

After editing shapes, you also need a local PHP environment to build the final script.

Let me know if you have any questions.
