### ISSUE TITLE
Sometimes the API returns weird face

### ISSUE THREAD

**Issue by zed-wong** [multiavatar/Multiavatar#16]
e.g. 
![image](https://user-images.githubusercontent.com/36271125/184578127-78cbb94f-6079-4dff-adc4-09d5e7ea36cc.png)

![image](https://user-images.githubusercontent.com/36271125/184578205-96d9ce1a-df16-4dde-8aad-1e8493f645d1.png)

Long hair person with a mustache is kind of weird. Maybe it's better to have a consistent sexual identityfication?

**Comment by giekaton** [comment]
In real life, some people identify themselves neither as male nor female. It's a non-binary gender.

I think it's good that there are non-binary avatars since they reflect real life.

**Comment by zed-wong** [comment]
> In real life, some people identify themselves neither as male nor female. It's a non-binary gender.
> 
> I think it's good that there are non-binary avatars since they reflect real life.

It's true though. But in most areas of the world, people are still used to consistent sexual identification. Since we're building products for most people, it might be better to have an argument to filter the image to avoid the possible uncomfortable feeling of the user.

**Comment by giekaton** [comment]
The ability to choose a specific gender avatar, as requested in the #1 issue, would give people more control when picking an avatar. But it's a complex feature to implement, and I'm currently working on the Multiavatar NFT collection.

**Comment by zed-wong** [comment]
Ok, thank you for replying.
