### ISSUE TITLE
是否可以从svg转换到文本（转换前输入的文字）的功能呢?

### ISSUE THREAD

**Issue by canye666** [multiavatar/Multiavatar#8]
从图像到文本的转换，我想可以用来做一些东西。

**Comment by giekaton** [comment]
If you can, write in English, or someone else please translate it. I have translated the message with Google Translate, but still can't understand the meaning.

**Comment by MapleCCC** [comment]
OP basically wants to ask whether it's possible to find the original string that generates a given avatar.

**Comment by giekaton** [comment]
No, a reverse is not possible. It's based on a SHA-256 cryptographic hash which is a one-way function.
